"""
Central configuration for the Story Bot.
Loads from environment variables (.env locally, GitHub Secrets in CI).
"""
import os
from dotenv import load_dotenv

load_dotenv()

# ── API Keys ──────────────────────────────────────────────
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
# Second Gemini key (different free project) — used for thumbnails so
# image generation doesn't share/exhaust the script-writing quota.
# When the primary key hits a rate limit, the thumbnail generator
# switches to this one immediately (no waiting).
GEMINI_API_KEY_2 = os.getenv("GEMINI_API_KEY_2", "")
HUGGINGFACE_API_KEY = os.getenv("HUGGINGFACE_API_KEY", "")
PEXELS_API_KEY = os.getenv("PEXELS_API_KEY", "")
PIXABAY_API_KEY = os.getenv("PIXABAY_API_KEY", "")

# ── Groq (FREE fallback LLM for script writing) ────────────
# When Gemini is rate-limited, scripts are written by Groq instead,
# so the bot never stalls. Free, no credit card: console.groq.com
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
# llama-3.3-70b-versatile was deprecated (Jun 2026); gpt-oss-120b is
# Groq's recommended replacement. Override via env if it changes again.
GROQ_MODEL = os.getenv("GROQ_MODEL", "openai/gpt-oss-120b")
GROQ_BASE_URL = "https://api.groq.com/openai/v1/chat/completions"

# ── Instagram ─────────────────────────────────────────────
INSTAGRAM_USERNAME = os.getenv("INSTAGRAM_USERNAME", "")
INSTAGRAM_PASSWORD = os.getenv("INSTAGRAM_PASSWORD", "")

# ── YouTube ───────────────────────────────────────────────
YOUTUBE_CLIENT_SECRETS = os.getenv("YOUTUBE_CLIENT_SECRETS_JSON", "")
YOUTUBE_TOKEN = os.getenv("YOUTUBE_TOKEN_JSON", "")

# ── Channel Settings ──────────────────────────────────────
CHANNEL_NAME = os.getenv("CHANNEL_NAME", "Kids Story Time")
# Hindi female neural voice
DEFAULT_VOICE = os.getenv("DEFAULT_VOICE", "hi-IN-SwaraNeural")
VIDEO_RESOLUTION = os.getenv("VIDEO_RESOLUTION", "1920x1080")
VIDEO_WIDTH, VIDEO_HEIGHT = map(int, VIDEO_RESOLUTION.split("x"))
FPS = int(os.getenv("FPS", "30"))
TIMEZONE = os.getenv("TIMEZONE", "Asia/Kolkata")

# ── Language ──────────────────────────────────────────────
STORY_LANGUAGE = "hi"          # ISO code
STORY_LANGUAGE_NAME = "Hindi"  # display name

# ── Upload Schedule (local time) ──────────────────────────
UPLOAD_TIMES = ["07:00", "13:00", "18:00"]

# ── Video Duration Target ─────────────────────────────────
TARGET_DURATION_MIN = 40
TARGET_DURATION_MAX = 45
WORDS_PER_MINUTE = 120   # Hindi narration is slightly slower
TARGET_WORD_COUNT = TARGET_DURATION_MIN * WORDS_PER_MINUTE  # ~4800

# ── Paths ─────────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(BASE_DIR, "src")
OUTPUT_DIR = os.path.join(BASE_DIR, "output")
ASSETS_DIR = os.path.join(BASE_DIR, "assets")
DATA_DIR = os.path.join(BASE_DIR, "data")
FONTS_DIR = os.path.join(ASSETS_DIR, "fonts")
MUSIC_DIR = os.path.join(ASSETS_DIR, "music")
OVERLAYS_DIR = os.path.join(ASSETS_DIR, "overlays")

for _d in [OUTPUT_DIR, ASSETS_DIR, DATA_DIR, FONTS_DIR, MUSIC_DIR, OVERLAYS_DIR]:
    os.makedirs(_d, exist_ok=True)

# ── Image Generation — Pollinations.ai (FREE, no API key) ──
# High-quality flux text-to-image. One image per scene, derived
# from each scene's English visual_prompt so visuals match the
# narration and change with the script.
POLLINATIONS_BASE = "https://image.pollinations.ai/prompt"
IMAGE_MODEL = "flux"           # best free model on Pollinations
IMAGE_WIDTH = 1024
IMAGE_HEIGHT = 576             # 16:9 for video scenes
THUMB_WIDTH = 1280
THUMB_HEIGHT = 720             # 16:9 YouTube thumbnail

# ── Thumbnail Generation — Gemini image model (uses your paid Gemini) ──
# Thumbnails are generated by Gemini for top quality, NOT Pollinations.
# "gemini-2.5-flash-image" (Nano Banana) is reliable + cheap (~$0.04/img).
# For maximum quality switch to "gemini-3-pro-image-preview" (Nano Banana Pro).
GEMINI_IMAGE_MODEL = "gemini-2.5-flash-image"

# Style strings injected into every prompt
CARTOON_STYLE = (
    "cartoon style, children's storybook illustration, vibrant colors, "
    "soft shading, friendly characters, Studio Ghibli inspired, whimsical, "
    "highly detailed, masterpiece, high quality"
)
GHIBLI_STYLE = (
    "Studio Ghibli style anime illustration, hand-painted watercolor look, "
    "dreamy soft pastel colors, Hayao Miyazaki, lush nature, beautiful "
    "detailed background, cinematic lighting, masterpiece, highly detailed"
)
NEGATIVE_STYLE = (
    "nsfw, nude, explicit, gore, blood, violence, realistic, photorealistic, "
    "blurry, low quality, distorted, deformed, ugly, extra fingers, "
    "bad anatomy, watermark, text, signature"
)

# Optional: HuggingFace token (no longer used for image inference,
# kept so existing imports/env stay valid).
HF_CARTOON_MODEL = "OEvortex/cartoon-style"
HF_GHIBLI_MODEL = "OEvortex/ghibli-style"

# ── Safety ────────────────────────────────────────────────
BLOCKED_KEYWORDS = [
    "nude", "naked", "explicit", "obscene", "violence gore",
    "drug", "weapon", "blood", "kill", "murder",
    "अश्लील", "नग्न", "हिंसा", "खून", "नशा", "हत्या",
]

def is_safe_content(text: str) -> bool:
    text_lower = text.lower()
    return not any(kw in text_lower for kw in BLOCKED_KEYWORDS)
