"""
Content Manager — the brain of the Story Bot.
Orchestrates the entire pipeline from AI-generated topic selection
to final upload on YouTube and Instagram.

All stories are in Hindi with a female narrator voice.
Topics are generated by Gemini AI — never repeated.
"""
import os
import sys
import json
import random
import logging
from datetime import datetime, timedelta, timezone
from typing import Optional

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from config import (
    OUTPUT_DIR, DATA_DIR, UPLOAD_TIMES, TIMEZONE,
    TARGET_DURATION_MIN, TARGET_DURATION_MAX,
)
from utils import (
    logger, ensure_dir, sanitize_filename,
    clean_output_dir, validate_content_safety,
)
from script_writer import ScriptWriter
from tts_engine import TTSEngine
from image_generator import ImageGenerator
from media_fetcher import MediaFetcher
from music_fetcher import MusicFetcher
from video_editor import VideoEditor
from thumbnail_gen import ThumbnailGenerator

PUBLISHED_FILE = os.path.join(DATA_DIR, "published.json")


class ContentManager:
    """Orchestrates the full automated Hindi content pipeline."""

    def __init__(self):
        self.script_writer = ScriptWriter()
        self.tts_engine = TTSEngine()
        self.image_generator = ImageGenerator()
        self.media_fetcher = MediaFetcher()
        self.music_fetcher = MusicFetcher()
        self.video_editor = VideoEditor()
        self.thumbnail_gen = ThumbnailGenerator()
        self.youtube_uploader = None
        self.instagram_poster = None
        self.published = self._load_published()

    # ── Data Management ────────────────────────────────────
    def _load_published(self) -> list[dict]:
        if os.path.exists(PUBLISHED_FILE):
            with open(PUBLISHED_FILE, "r") as f:
                return json.load(f)
        return []

    def _save_published(self):
        ensure_dir(DATA_DIR)
        with open(PUBLISHED_FILE, "w") as f:
            json.dump(self.published, f, indent=2)

    def _get_used_topics(self) -> list[str]:
        """Return list of all topic titles ever published."""
        return [p.get("topic", "") for p in self.published]

    # ── AI Topic Selection (replaces static topics.json) ───
    def _select_daily_topics(self, count: int = 3) -> list[dict]:
        """
        Ask Gemini to generate unique Hindi topics that haven't
        been used before. Mix: 2 children's + 1 horror.

        Returns list of dicts:
          {"title": "हिंदी शीर्षक", "type": "children"|"horror", "description": "..."}
        """
        used_topics = self._get_used_topics()
        logger.info(f"पिछली प्रकाशित कहानियाँ: {len(used_topics)}")

        selected = []

        # Generate 2 children's topics
        children_topics = self.script_writer.generate_unique_topics(
            used_topics=used_topics,
            count=2,
            topic_type="children",
        )
        for t in children_topics:
            t["type"] = "children"
            selected.append(t)
            used_topics.append(t.get("title", ""))

        # Generate 1 horror topic
        horror_topics = self.script_writer.generate_unique_topics(
            used_topics=used_topics,
            count=1,
            topic_type="horror",
        )
        for t in horror_topics:
            t["type"] = "horror"
            selected.append(t)
            used_topics.append(t.get("title", ""))

        # If AI failed to generate enough, log warning
        if len(selected) < count:
            logger.warning(
                f"AI केवल {len(selected)} विषय बना सका (लक्ष्य: {count})"
            )

        logger.info(f"आज के विषय चुने गए:")
        for i, t in enumerate(selected):
            logger.info(f"  {i+1}. [{t['type']}] {t['title']}")

        return selected

    # ── Publish Time Calculation ───────────────────────────
    def _calculate_publish_time(self, slot: int) -> str:
        from zoneinfo import ZoneInfo
        tz = ZoneInfo(TIMEZONE)
        now = datetime.now(tz)
        time_map = {0: 7, 1: 13, 2: 18}
        hour = time_map.get(slot, 7)
        target = now.replace(hour=hour, minute=0, second=0, microsecond=0)
        if target <= now:
            target += timedelta(days=1)
        return target.isoformat()

    # ── Instagram Reel Overlay ─────────────────────────────
    def _add_reel_text_overlay(
        self, reel_path: str, output_path: str, story_title: str
    ) -> str:
        import subprocess
        safe_title = story_title.replace(":", "\\:").replace("'", "\\'")

        args = [
            "-i", reel_path,
            "-vf",
            f"drawtext=text='{safe_title}':"
            f"fontcolor=white:fontsize=42:x=(w-text_w)/2:y=120:"
            f"box=1:boxcolor=black@0.6:boxborderw=15,"
            f"drawtext=text='Full story YouTube par dekho!':"
            f"fontcolor=yellow:fontsize=36:x=(w-text_w)/2:y=h-120:"
            f"box=1:boxcolor=black@0.6:boxborderw=12",
            "-c:a", "copy",
            "-c:v", "libx264",
            "-preset", "ultrafast",
            "-crf", "25",
            "-pix_fmt", "yuv420p",
            output_path,
        ]

        cmd = ["ffmpeg", "-y", "-hide_banner", "-loglevel", "warning"] + args
        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode == 0 and os.path.exists(output_path):
            return output_path
        else:
            logger.warning(f"Reel overlay failed, using original")
            return reel_path

    # ── Lazy Initializers ──────────────────────────────────
    def _init_youtube(self):
        if self.youtube_uploader is not None:
            return
        try:
            from youtube_uploader import YouTubeUploader
            self.youtube_uploader = YouTubeUploader()
            logger.info("YouTube uploader initialized")
        except Exception as e:
            logger.error(f"Failed to initialize YouTube uploader: {e}")
            self.youtube_uploader = None

    def _init_instagram(self):
        if self.instagram_poster is not None:
            return
        try:
            from instagram_poster import InstagramPoster
            from config import INSTAGRAM_USERNAME, INSTAGRAM_PASSWORD
            if INSTAGRAM_USERNAME and INSTAGRAM_PASSWORD:
                self.instagram_poster = InstagramPoster(
                    INSTAGRAM_USERNAME, INSTAGRAM_PASSWORD
                )
                logger.info("Instagram poster initialized")
            else:
                logger.warning("Instagram credentials not set, skipping Reels")
        except Exception as e:
            logger.error(f"Failed to initialize Instagram poster: {e}")
            self.instagram_poster = None

    # ── Single Video Pipeline ──────────────────────────────
    def _process_single_video(
        self,
        topic: dict,
        slot: int,
        date_str: str,
    ) -> Optional[dict]:
        """
        Process a single AI-generated Hindi topic through the
        full pipeline.
        """
        title = topic["title"]
        topic_type = topic["type"]
        job_id = f"{date_str}_{slot}_{sanitize_filename(title)}"
        job_dir = os.path.join(OUTPUT_DIR, job_id)
        ensure_dir(job_dir)

        logger.info(f"\n{'='*60}")
        logger.info(f"वीडियो {slot+1}/3: {title}")
        logger.info(f"प्रकार: {topic_type} | Job: {job_id}")
        logger.info(f"{'='*60}\n")

        try:
            # ── Step 1: Generate Script (Hindi) ──
            logger.info("[1/8] Gemini से हिंदी स्क्रिप्ट बन रही है...")
            script = self.script_writer.generate_script(
                topic=topic,
                topic_type=topic_type,
            )

            script_path = os.path.join(job_dir, "script.json")
            with open(script_path, "w") as f:
                json.dump(script, f, indent=2, ensure_ascii=False)

            scenes = script.get("scenes", [])
            video_title = script.get("title", title)
            description = script.get("description", "")
            tags = script.get("tags", [])

            logger.info(
                f"  स्क्रिप्ट: {len(scenes)} दृश्य, "
                f"~{sum(len(s.get('narration','').split()) for s in scenes)} शब्द"
            )

            # ── Step 2: Generate TTS (Hindi female + emotions) ──
            logger.info("[2/8] हिंदी महिला आवाज़ में भावनात्मक ऑडियो बन रहा है...")
            audio_results = self.tts_engine.generate_full_narration(
                scenes, job_dir
            )

            # ── Step 3: Generate Cartoon Images ──
            logger.info("[3/8] कार्टून दृश्य बन रहे हैं...")
            image_paths = self.image_generator.generate_all_images(
                scenes, job_dir
            )

            # ── Step 4: Fetch Stock Media ──
            logger.info("[4/8] Stock media लाया जा रहा है...")
            stock_query = "cartoon animation" if topic_type == "children" else "dark forest"
            stock_videos = self.media_fetcher.fetch_stock_media(
                query=stock_query, job_dir=job_dir,
                media_type="video", count=2,
            )

            # ── Step 5: Fetch Background Music ──
            logger.info("[5/8] Background music लाया जा रहा है...")
            moods = [s.get("mood", "neutral") for s in scenes]
            dominant_mood = max(set(moods), key=moods.count) if moods else "neutral"
            music_path = self.music_fetcher.fetch_background_music(
                mood=dominant_mood, job_dir=job_dir
            )

            # ── Step 6: Assemble Video ──
            logger.info("[6/8] FFmpeg से वीडियो बन रहा है...")
            scene_assets = []
            for i, scene in enumerate(scenes):
                asset = {
                    "image_path": image_paths[i] if i < len(image_paths) else None,
                    "audio_path": audio_results[i]["audio_path"],
                    "srt_path": audio_results[i]["srt_path"],
                    "stock_videos": [],
                }
                if stock_videos and i % 5 == 0 and i < len(scenes):
                    asset["stock_videos"] = [stock_videos[i % len(stock_videos)]]
                scene_assets.append(asset)

            final_video = self.video_editor.assemble_video(
                scenes=scenes,
                scene_assets=scene_assets,
                music_path=music_path,
                job_dir=job_dir,
                video_title=sanitize_filename(video_title),
            )

            # ── Step 7: Generate Thumbnail ──
            logger.info("[7/8] Ghibli-style thumbnail बन रहा है...")
            story_summary = script.get("description", "")[:200]
            first_image = image_paths[0] if image_paths else None
            thumbnail_path = self.thumbnail_gen.generate_thumbnail(
                title=video_title,
                story_summary=story_summary,
                scene_image_path=first_image,
                job_dir=job_dir,
            )

            # ── Step 8: Upload to YouTube ──
            logger.info("[8/8] YouTube पर अपलोड हो रहा है...")
            video_id = None
            youtube_url = None
            publish_time = self._calculate_publish_time(slot)

            self._init_youtube()
            if self.youtube_uploader:
                video_id = self.youtube_uploader.upload_video(
                    video_path=final_video,
                    title=video_title,
                    description=description,
                    tags=tags,
                    thumbnail_path=thumbnail_path,
                    publish_at=publish_time,
                    made_for_kids=(topic_type == "children"),
                )
                youtube_url = self.youtube_uploader.get_video_url(video_id)
                logger.info(f"  YouTube: {youtube_url} (प्रकाशित: {publish_time})")
            else:
                logger.warning("  YouTube अपलोड छोड़ा गया (कोई credentials नहीं)")
                youtube_url = "https://youtube.com/@yourchannel"

            # ── Create & Post Instagram Reel ──
            logger.info("Instagram Reel promo बन रहा है...")
            reel_path = self.video_editor.create_instagram_reel(
                full_video_path=final_video,
                job_dir=job_dir,
                reel_duration=30,
            )

            reel_with_overlay = os.path.join(job_dir, "reels", "promo_reel_final.mp4")
            reel_final = self._add_reel_text_overlay(
                reel_path, reel_with_overlay, video_title
            )

            self._init_instagram()
            reel_posted = False
            if self.instagram_poster and youtube_url:
                caption = self.instagram_poster.generate_reel_caption(
                    story_title=video_title,
                    youtube_url=youtube_url,
                    topic_type=topic_type,
                )
                reel_posted = self.instagram_poster.post_reel(
                    video_path=reel_final,
                    caption=caption,
                )
            else:
                logger.warning("  Instagram posting छोड़ा गया")

            # ── Record Published Content ──
            record = {
                "date": date_str,
                "slot": slot,
                "topic": title,
                "topic_type": topic_type,
                "video_title": video_title,
                "video_id": video_id,
                "youtube_url": youtube_url,
                "publish_time": publish_time,
                "reel_posted": reel_posted,
                "scene_count": len(scenes),
            }
            self.published.append(record)
            self._save_published()

            # ── Cleanup ──
            logger.info("Intermediate files साफ किए जा रहे हैं...")
            clean_output_dir(job_id)

            logger.info(f"\n✓ वीडियो {slot+1} पूर्ण: {video_title}")
            return record

        except Exception as e:
            logger.error(f"\n✗ '{title}' प्रोसेस करने में विफल: {e}")
            import traceback
            logger.debug(traceback.format_exc())
            clean_output_dir(job_id)
            return None

    # ── Main Entry Point ───────────────────────────────────
    def run_daily_pipeline(self, num_videos: int = 3):
        """Run the full daily pipeline: AI topics → Hindi scripts → upload."""
        date_str = datetime.now().strftime("%Y-%m-%d")
        logger.info(f"\n{'#'*60}")
        logger.info(f"# दैनिक पाइपलाइन शुरू — {date_str}")
        logger.info(f"# लक्ष्य: {num_videos} वीडियो (हिंदी)")
        logger.info(f"{'#'*60}\n")

        # AI generates unique topics
        topics = self._select_daily_topics(count=num_videos)

        if not topics:
            logger.error("AI विषय नहीं बना सका!")
            return

        results = []
        for i, topic in enumerate(topics):
            result = self._process_single_video(
                topic=topic,
                slot=i,
                date_str=date_str,
            )
            results.append(result)

        success_count = sum(1 for r in results if r is not None)
        fail_count = len(results) - success_count

        logger.info(f"\n{'#'*60}")
        logger.info(f"# दैनिक पाइपलाइन पूर्ण")
        logger.info(f"# सफल: {success_count}/{len(results)}")
        if fail_count:
            logger.info(f"# विफल: {fail_count}")
        logger.info(f"{'#'*60}\n")

        for r in results:
            if r:
                logger.info(
                    f"  [{r['slot']+1}] {r['video_title']} → "
                    f"{r.get('youtube_url', 'N/A')} "
                    f"(प्रकाशित: {r.get('publish_time', 'N/A')})"
                )


if __name__ == "__main__":
    manager = ContentManager()
    manager.run_daily_pipeline()
